name: Laravel CI/CD with Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ§¾ Checkout repo
      uses: actions/checkout@v3

    - name: ğŸ˜ Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: ğŸ“¦ Install dependencies
      run: |
        cd tugas-manager
        composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: âš™ï¸ Copy .env example
      run: |
        cp tugas-manager/.env.example tugas-manager/.env

    - name: ğŸ”‘ Generate Laravel Key
      run: |
        cd tugas-manager
        php artisan key:generate

    - name: ğŸ³ Build Docker image
      run: |
        docker build -t cloud-computing-app ./tugas-manager
